import aspn23

from pntos.cobra.config import AspnMessageType

# Map AspnMessageType enum to type[AspnBase] class
ASPN_MESSAGE_TYPE_MAP: dict[AspnMessageType, type[aspn23.AspnBase]] = {
    AspnMessageType.ASPN_MEASUREMENT_ACCUMULATED_DISTANCE_TRAVELED: aspn23.MeasurementAccumulatedDistanceTraveled,
    AspnMessageType.ASPN_MEASUREMENT_ALTITUDE: aspn23.MeasurementAltitude,
    AspnMessageType.ASPN_MEASUREMENT_ANGULAR_VELOCITY: aspn23.MeasurementAngularVelocity,
    AspnMessageType.ASPN_MEASUREMENT_ANGULAR_VELOCITY_1D: aspn23.MeasurementAngularVelocity1D,
    AspnMessageType.ASPN_MEASUREMENT_ATTITUDE_2D: aspn23.MeasurementAttitude2D,
    AspnMessageType.ASPN_MEASUREMENT_ATTITUDE_3D: aspn23.MeasurementAttitude3D,
    AspnMessageType.ASPN_MEASUREMENT_BAROMETER: aspn23.MeasurementBarometer,
    AspnMessageType.ASPN_MEASUREMENT_DELTA_POSITION: aspn23.MeasurementDeltaPosition,
    AspnMessageType.ASPN_MEASUREMENT_DELTA_RANGE: aspn23.MeasurementDeltaRange,
    AspnMessageType.ASPN_MEASUREMENT_DELTA_RANGE_TO_POINT: aspn23.MeasurementDeltaRangeToPoint,
    AspnMessageType.ASPN_MEASUREMENT_DIRECTION_2D_TO_POINTS: aspn23.MeasurementDirection2DToPoints,
    AspnMessageType.ASPN_MEASUREMENT_DIRECTION_3D_TO_POINTS: aspn23.MeasurementDirection3DToPoints,
    AspnMessageType.ASPN_MEASUREMENT_DIRECTION_OF_MOTION_2D: aspn23.MeasurementDirectionOfMotion2D,
    AspnMessageType.ASPN_MEASUREMENT_DIRECTION_OF_MOTION_3D: aspn23.MeasurementDirectionOfMotion3D,
    AspnMessageType.ASPN_MEASUREMENT_FREQUENCY_DIFFERENCE: aspn23.MeasurementFrequencyDifference,
    AspnMessageType.ASPN_MEASUREMENT_HEADING: aspn23.MeasurementHeading,
    AspnMessageType.ASPN_MEASUREMENT_IMAGE: aspn23.MeasurementImage,
    AspnMessageType.ASPN_MEASUREMENT_IMU: aspn23.MeasurementImu,
    AspnMessageType.ASPN_MEASUREMENT_MAGNETIC_FIELD: aspn23.MeasurementMagneticField,
    AspnMessageType.ASPN_MEASUREMENT_MAGNETIC_FIELD_MAGNITUDE: aspn23.MeasurementMagneticFieldMagnitude,
    AspnMessageType.ASPN_MEASUREMENT_POSITION: aspn23.MeasurementPosition,
    AspnMessageType.ASPN_MEASUREMENT_POSITION_ATTITUDE: aspn23.MeasurementPositionAttitude,
    AspnMessageType.ASPN_MEASUREMENT_POSITION_VELOCITY_ATTITUDE: aspn23.MeasurementPositionVelocityAttitude,
    AspnMessageType.ASPN_MEASUREMENT_RANGE_RATE_TO_POINT: aspn23.MeasurementRangeRateToPoint,
    AspnMessageType.ASPN_MEASUREMENT_RANGE_TO_POINT: aspn23.MeasurementRangeToPoint,
    AspnMessageType.ASPN_MEASUREMENT_SATNAV: aspn23.MeasurementSatnav,
    AspnMessageType.ASPN_MEASUREMENT_SATNAV_SUBFRAME: aspn23.MeasurementSatnavSubframe,
    AspnMessageType.ASPN_MEASUREMENT_SATNAV_WITH_SV_DATA: aspn23.MeasurementSatnavWithSvData,
    AspnMessageType.ASPN_MEASUREMENT_SPECIFIC_FORCE_1D: aspn23.MeasurementSpecificForce1D,
    AspnMessageType.ASPN_MEASUREMENT_SPEED: aspn23.MeasurementSpeed,
    AspnMessageType.ASPN_MEASUREMENT_TDOA_1TX_2RX: aspn23.MeasurementTdoa1Tx2Rx,
    AspnMessageType.ASPN_MEASUREMENT_TDOA_2TX_1RX: aspn23.MeasurementTdoa2Tx1Rx,
    AspnMessageType.ASPN_MEASUREMENT_TEMPERATURE: aspn23.MeasurementTemperature,
    AspnMessageType.ASPN_MEASUREMENT_TIME: aspn23.MeasurementTime,
    AspnMessageType.ASPN_MEASUREMENT_TIME_DIFFERENCE: aspn23.MeasurementTimeDifference,
    AspnMessageType.ASPN_MEASUREMENT_TIME_FREQUENCY_DIFFERENCE: aspn23.MeasurementTimeFrequencyDifference,
    AspnMessageType.ASPN_MEASUREMENT_VELOCITY: aspn23.MeasurementVelocity,
    AspnMessageType.ASPN_METADATA_BEIDOU_EPHEMERIS: aspn23.MetadataBeidouEphemeris,
    AspnMessageType.ASPN_METADATA_GALILEO_EPHEMERIS: aspn23.MetadataGalileoEphemeris,
    AspnMessageType.ASPN_METADATA_GENERIC: aspn23.MetadataGeneric,
    AspnMessageType.ASPN_METADATA_GLONASS_EPHEMERIS: aspn23.MetadataGlonassEphemeris,
    AspnMessageType.ASPN_METADATA_GPS_CNAV_EPHEMERIS: aspn23.MetadataGpsCnavEphemeris,
    AspnMessageType.ASPN_METADATA_GPS_IONO_UTC_PARAMETERS: aspn23.MetadataGpsIonoUtcParameters,
    AspnMessageType.ASPN_METADATA_GPS_LNAV_EPHEMERIS: aspn23.MetadataGpsLnavEphemeris,
    AspnMessageType.ASPN_METADATA_GPS_MNAV_EPHEMERIS: aspn23.MetadataGpsMnavEphemeris,
    AspnMessageType.ASPN_METADATA_IMAGE_FEATURES: aspn23.MetadataImageFeatures,
    AspnMessageType.ASPN_METADATA_IMU: aspn23.MetadataImu,
    AspnMessageType.ASPN_METADATA_MAGNETIC_FIELD: aspn23.MetadataMagneticField,
    AspnMessageType.ASPN_METADATA_SATNAV_OBS: aspn23.MetadataSatnavObs,
}
