---
workflow:
  rules:
  # Never run merge request pipelines
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
  # Only run on git.aspn.us
  - if: $CI_SERVER_HOST == "git.aspn.us"

variables:
  GIT_CLEAN_FLAGS: -xdff
  UV_INDEX: https://gitlab-ci-token:${CI_JOB_TOKEN}@git.aspn.us/api/v4/projects/94/packages/pypi/simple

default:
    retry:
      max: 2 # (2 retry maximum, up to 3 runs in total)
      when: runner_system_failure
      exit_codes: 128
    before_script:

        # Clone only if empty directory
        - |
            if ! [ "$(ls -A)" ]; then
                git clone $CI_REPOSITORY_URL .
            fi
        - git remote set-url origin $CI_REPOSITORY_URL
        - git --no-optional-locks fetch --prune
        - git reset --hard "$CI_COMMIT_SHA"
        - git clean "$GIT_CLEAN_FLAGS" || true

        # If this is a branch pipeline, attempt to merge with master/target branch, but keep going
        # if it fails.
        - |
            if [[ ! -z "${CI_COMMIT_BRANCH}" ]]; then
                git merge origin/"${TARGET_BRANCH:-$CI_DEFAULT_BRANCH}" || true
                git reset --hard
                git clean "$GIT_CLEAN_FLAGS"
            fi

        # Grab URL with CI token, which is of the form:
        # https://gitlab-ci-token:[MASKED]@git.aspn.us/pntos/pntos.git
        - export TOKEN_URL="$(echo $CI_REPOSITORY_URL | sed -E 's/(.*git.aspn.us\/).*/\1/g')"

        # Modify the pyproject.toml and requirements*.txt dependencies to use the CI token URL.
        - find pntos-* -type f -name "pyproject.toml" -exec sed -i -e "s|git+ssh://git@git.aspn.us/|git+$TOKEN_URL|g" {} \+
        - find . -type f -name "requirements*.txt" -exec sed -i -e "s|git+ssh://git@git.aspn.us/|git+$TOKEN_URL|g" {} \+

        # Build docker container
        - docker pull ubuntu:24.04
        - export DOCKER_IMAGE="$LOCAL_REGISTRY_CACHE/pntos-python"
        - docker build --cache-from $DOCKER_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 -t $DOCKER_IMAGE -f Dockerfile .
        - docker push $DOCKER_IMAGE

stages:
    - check
    - deploy

ruff check:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -v $(pwd):/work -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE "uv sync -v && ruff check"

ruff format:
    stage: check
    tags:
        - linux-light-runner
    script:
        # Run the formatter to see if it produces a diff.
        - docker run --rm -v $(pwd):/work -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE "uv sync -v && ruff format"
        # Don't let modification to the pyproject.toml, requirements*.txt, or uv.lock files produce a diff.
        - git checkout -- $(git ls-files | grep pyproject.toml)
        - git checkout -- $(git ls-files | grep requirements.txt)
        - git checkout -- $(git ls-files | grep requirements-minimal.txt)
        - git checkout -- $(git ls-files | grep uv.lock)
        # If there's a diff, fail the stage.
        - git diff --exit-code

requirements up-to-date:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        # Generate uv.lock
        - docker exec pntos-python uv sync -v
        # Generate requirements*.txt files
        - docker exec pntos-python uv export --frozen --no-dev --all-packages --no-hashes > requirements-minimal.txt
        - docker exec pntos-python uv export --frozen --all-packages --no-hashes > requirements.txt
        # Revert URL surgery to sources and generated output
        - find pntos-* -type f -name "pyproject.toml" -exec sed -i -e "s|git+$TOKEN_URL|git+ssh://git@git.aspn.us/|g" {} \+
        - find . -type f -name "requirements*.txt" -exec sed -i -e "s|git+https://|git+ssh://git@|g" {} \+
        - sed -i -e "s|https://git.aspn.us/pntos|ssh://git@git.aspn.us/pntos|g" uv.lock
        # If there's still a diff, then there's unsynced changes; fail the job.
        - git diff --exit-code

Python 3.10 Test:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -v $(pwd):/work -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE "uv sync -v && pytest --cov --cov-fail-under=75 --cov-report={term,html}  --cov-config=.coveragerc"
    coverage:
        '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
      paths:
        - htmlcov/*

Python 3.13 Test:
    stage: check
    tags:
        - linux-light-runner
    script:
        # Switch the Python version to 3.13
        - echo 3.13 > .python-version
        - docker run --rm -v $(pwd):/work -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE "uv sync -v && pytest --cov --cov-fail-under=75 --cov-report={term,html}  --cov-config=.coveragerc"

mypy:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        - docker exec pntos-python mypy pntos-api --no-implicit-reexport
        - docker exec pntos-python mypy pntos-cobra --no-implicit-reexport
        - docker exec pntos-python mypy apps --no-implicit-reexport

documentation check:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --workdir /work/docs --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        # Build the documentation
        - docker exec -e TZ=UTC pntos-python make html
    artifacts:
        expose_as: "documentation"
        paths:
        - docs/build/html/index.html  # must be first, expose_as links to the first entry
        - docs/build/html # ..but all the other files *also* need to be in the archive

GPS INS App:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        - docker exec pntos-python postprocessing/run_app_and_record_data.py
    artifacts:
        paths:
            - pntos_output/

pip workflow check:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python python3 -m venv /work/.venv
        - docker exec pntos-python .venv/bin/pip install -v -r requirements.txt --extra-index-url=${UV_INDEX}
        - docker exec pntos-python postprocessing/run_app_and_record_data.py

pages:
    stage: deploy
    tags: [linux-light-runner]
    before_script: []
    script:
        - rm -rf public
        - mkdir -p public
        - cp -r docs/build/html/* public
    needs:
        - documentation check
    only:
        - main
    artifacts:
        paths:
            - public
