---
workflow:
  rules:
  # Never run merge request pipelines
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
  # Only run on git.aspn.us
  - if: $CI_SERVER_HOST == "git.aspn.us"

variables:
  GIT_CLEAN_FLAGS: -xdff
  UV_INDEX: https://gitlab-ci-token:${CI_JOB_TOKEN}@git.aspn.us/api/v4/projects/94/packages/pypi/simple

default:
    retry:
      max: 2 # (2 retry maximum, up to 3 runs in total)
      when: runner_system_failure
      exit_codes: 128
    before_script:

        # Clone only if empty directory
        - |
            if ! [ "$(ls -A)" ]; then
                git clone $CI_REPOSITORY_URL .
            fi
        - git remote set-url origin $CI_REPOSITORY_URL
        - git --no-optional-locks fetch --prune
        - git reset --hard "$CI_COMMIT_SHA"
        - git clean "$GIT_CLEAN_FLAGS" || true

        # If this is a branch pipeline, attempt to merge with master/target branch, but keep going
        # if it fails.
        - |
            if [[ ! -z "${CI_COMMIT_BRANCH}" ]]; then
                git merge origin/"${TARGET_BRANCH:-$CI_DEFAULT_BRANCH}" || true
                git reset --hard
                git clean "$GIT_CLEAN_FLAGS"
            fi

        # Grab URL with CI token, which is of the form:
        # https://gitlab-ci-token:[MASKED]@git.aspn.us/pntos/pntos.git
        - export TOKEN_URL="$(echo $CI_REPOSITORY_URL | sed -E 's/(.*git.aspn.us\/).*/\1/g')"

        # Build docker container
        - docker pull ros:jazzy-ros-base
        - export DOCKER_IMAGE="$LOCAL_REGISTRY_CACHE/pntos-python"
        - docker build --cache-from $DOCKER_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg TOKEN_URL=$TOKEN_URL -t $DOCKER_IMAGE - < Dockerfile
        - docker push $DOCKER_IMAGE

stages:
    - check
    - deploy

ruff check:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -v $(pwd):/work -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE "uv sync -v && ruff check"

ruff format:
    stage: check
    tags:
        - linux-light-runner
    script:
        # Run the formatter to see if it produces a diff.
        - docker run --rm -v $(pwd):/work -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE "uv sync -v && ruff format"
        # If there's a diff, fail the stage.
        - git diff --exit-code

app and orchestration synchronization:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        # Run sync check script
        - util/check_sync.sh

requirements up-to-date:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        # Generate uv.lock
        - docker exec pntos-python uv sync -v
        # Generate requirements*.txt files
        - docker exec pntos-python uv export --frozen --no-dev --all-packages --no-hashes > requirements-minimal.txt
        - docker exec pntos-python uv export --frozen --all-packages --no-hashes > requirements.txt
        # If there's still a diff, then there's unsynced changes; fail the job.
        - git diff --exit-code

Python 3.10 Test:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -v $(pwd):/work -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE "uv sync -v && pytest --cov --cov-fail-under=75 --cov-report={term,html}  --cov-config=.coveragerc"
    coverage:
        '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
      paths:
        - htmlcov/*

Python 3.13 Test:
    stage: check
    tags:
        - linux-light-runner
    script:
        # Switch the Python version to 3.13
        - echo 3.13 > .python-version
        - docker run --rm -v $(pwd):/work -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE "uv sync -v && pytest --cov --cov-fail-under=75 --cov-report={term,html}  --cov-config=.coveragerc"

ASPN-ROS Test:
    stage: check
    tags:
        - linux-light-runner
    script:
        # Switch the Python version to 3.12 (for Jazzy compatibility)
        - echo 3.12 > .python-version
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        - docker exec pntos-python git clone --depth 1 git@git.aspn.us:pntos/firehose-outputs.git
        - docker exec pntos-python bash -c ". firehose-outputs/ros_devel/jazzy/setup.bash && pytest pntos-cobra/tests/test_aspn_ros.py"

mypy:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        - docker exec pntos-python mypy pntos-api --no-implicit-reexport
        - docker exec pntos-python mypy pntos-cobra --no-implicit-reexport
        - docker exec pntos-python mypy apps --no-implicit-reexport

documentation check:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        # Build the documentation
        - docker exec -e TZ=UTC pntos-python sphinx-build --exception-on-warning docs/source/ docs/build/
    artifacts:
        expose_as: "documentation"
        paths:
        - docs/build/index.html  # must be first, expose_as links to the first entry
        - docs/build # ..but all the other files *also* need to be in the archive

link check:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        # Check external links in the documentation
        - docker exec -e TZ=UTC pntos-python sphinx-build -b linkcheck --exception-on-warning docs/source/ docs/build/

GPS INS App:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        - docker exec pntos-python postprocessing/run_app_and_record_data.py
    artifacts:
        paths:
            - pntos_output/

GPS INS Velocity App:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        - docker exec pntos-python postprocessing/run_app_and_record_data.py fusion_gps_vel_ins
    artifacts:
        paths:
            - pntos_output/

GPS INS ROS App:
    stage: check
    tags:
        - linux-light-runner
    script:
        # Switch the Python version to 3.12 (for Jazzy compatibility)
        - echo 3.12 > .python-version
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        - docker exec pntos-python git clone --depth 1 git@git.aspn.us:pntos/firehose-outputs.git
        - docker exec pntos-python bash -c ". firehose-outputs/ros_devel/jazzy/setup.bash && postprocessing/run_app_and_record_data_ros.py"
    artifacts:
        paths:
            - pntos_output/

pip workflow check:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python python3 -m venv /work/.venv
        - docker exec pntos-python .venv/bin/pip install -v -r requirements.txt --extra-index-url=${UV_INDEX}
        - docker exec pntos-python postprocessing/run_app_and_record_data.py

copyright year check:
    stage: check
    tags:
        - linux-light-runner
    allow_failure: true
    script:
        - (! grep --color -i "copyright.*$(( $(date +%Y) - 1 ))" $(git ls-files))

build wheels:
    stage: check
    tags:
        - linux-light-runner
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python uv sync -v
        - docker exec pntos-python uv build pntos-api
        - docker exec pntos-python uv build pntos-cobra
    artifacts:
        paths:
            - dist/pntos*.whl

pages:
    stage: deploy
    tags: [linux-light-runner]
    before_script: []
    script:
        - rm -rf public
        - mkdir -p public
        - cp -r docs/build/* public
    needs:
        - documentation check
    only:
        - main
    artifacts:
        paths:
            - public

deploy wheels:
    stage: deploy
    tags:
        - linux-light-runner
    only:
        - main
    needs:
        - build wheels
    variables:
        # Don't clean artifacts from previous job
        GIT_CLEAN_FLAGS: -f
    script:
        - docker run --rm -dit -v $(pwd):/work --name pntos-python -e UV_INDEX=${UV_INDEX} $DOCKER_IMAGE bash
        - docker exec pntos-python python3 -m venv /work/.venv
        - docker exec pntos-python .venv/bin/pip install twine
        - export REPO_URL=${CI_API_V4_URL}/projects/94/packages/pypi
        - docker exec pntos-python twine upload
            --repository-url ${REPO_URL}
            --username gitlab-ci-token
            --password ${CI_JOB_TOKEN}
            --skip-existing
            dist/pntos*.whl
