[project]
name = "pntos-python"
version = "2.1.0-0.dev0"
description = "A meta package for pntOS that contains the components of pntOS."
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
authors = [ { name = "IS4S", email = "pntos@is4s.com" } ]
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "matplotlib",
    "navanalysis-lcm>=0.1.5",
    "navanalysis-ros>=0.1.2",
    "pntos-api",
    "pntos-cobra",
    "pntos-cobra-apps",
    "pntos-extras",
    "pntos-python-datasets-lcm==0.1.0",
    "pntos-python-datasets-ros==0.1.0",
    "typing-extensions>=4.14.1",
]

[dependency-groups]
dev = [
    "gitpython==3.1.44",
    "ipython>=8.24",
    "libclang>=18.1.1",
    "myst-parser>=4",
    "pip>=24",
    "pntos-cobra-docs-data",
    "pyproject-fmt==2.25.3",
    "pytest>=8.2",
    "pytest-cov>=6",
    "ruff==0.16.0",
    "setuptools>=82.0.1",
    "sphinx>=7.3.7",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-rtd-theme>=3.0.2",
    "ty==0.0.64",
]

[tool.uv]
sources.pntos-api = { workspace = true }
sources.pntos-cobra = { workspace = true }
sources.pntos-cobra-apps = { workspace = true }
sources.pntos-extras = { workspace = true }
package = false
workspace.members = [ "pntos-api", "pntos-cobra", "pntos-cobra-apps", "pntos-extras" ]

[tool.ruff]
format.quote-style = "single"
lint.select = [
    "ANN",
    "B",
    "BLE",
    "C4",
    "COM",
    "D",
    "DTZ",
    "E",
    "F",
    "FA",
    "FLY",
    "FURB",
    "G",
    "I",
    "ICN",
    "INT",
    "LOG",
    "NPY",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PTH",
    "RET",
    "RSE",
    "RUF",
    "SIM",
    "SLOT",
    "T10",
    "TID",
    "UP",
    "W",
]
lint.ignore = [
    "COM812",
    "D212",
    "D417",
    "E501",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0917",
]
lint.per-file-ignores."*/tests/*" = [
    "ANN001",
    "B008",
    "D100",
    "D101",
    "D102",
    "D107",
    "NPY",
    "PGH003",
    "PLC0415",
    "PLR0915",
    "PLR2004",
    "PLW0602",
    "PLW0603",
]
lint.per-file-ignores."docs/*" = [ "D" ]
lint.per-file-ignores."internal.py" = [ "PLC0414" ]
lint.per-file-ignores."pntos-api/*" = [ "PIE" ]
lint.per-file-ignores."pntos-cobra-apps/*" = [ "D" ]
lint.per-file-ignores."pntos-cobra/*" = [ "D" ]
lint.per-file-ignores."pntos-extras/*" = [ "D" ]
lint.per-file-ignores."postprocessing/*" = [ "D" ]
lint.per-file-ignores."util/*" = [ "D", "F" ]
lint.isort.combine-as-imports = true
lint.pydocstyle.convention = "google"

[tool.ty]
src.exclude = [
    "pntos-cobra/src/pntos/cobra/dummy_plugins/*",
    "pntos-cobra/src/pntos/cobra/tutorial_plugins/*",
]
rules.all = "error"
rules.missing-type-argument = "ignore"
analysis.strict-equality-semantics = false

[tool.pytest]
# NOTE: while coverage flags are provided here, coverage is not enabled as it doesn't work when
# debugging tests. To enable coverage, pass `--cov` flag when running pytest, and the flags below
# will all be included by default.
ini_options.addopts = [
    "-p no:launch_ros",
    "-p no:launch_testing",
    "--no-cov-on-fail",
    "--cov-fail-under=75",
    "--cov-report=term",
    "--cov-report=html",
]

[tool.coverage]
run.omit = [
    # ASPN-ROS
    "*/ros_devel/*",
    # upstream ROS
    "/opt/ros/*",
    "pntos-api/*",
    # App-running utils
    "pntos-cobra/src/pntos/cobra/utils/apps.py",
]
